#!/usr/bin/env node

/**
 * ./cipher-test
 * Test the cipher transformation
 * for: <https://github.com/lduran2/aes-blocksize512>
 * date: 2018-10-21 T00:26
 * by: Leomar Durán <https://github.com/lduran2>
 */

'use strict';

const state = require('./state.js');
const cipher = require('./cipher.js');
const ints = require('./ints.js');

/* the input plaintext */
const text = state.toStateArray4(
	[ 0, 4,  8, 12,
	  1, 5,  9, 13,
	  2, 6, 10, 14,
	  3, 7, 11, 15 ],
	4
);

console.log('Test subBytes:')
console.log(state.forEach(text, ((el, _0, _1, _2, _3) => (ints.toHexString(el, 2)))));
console.log();
console.log(state.forEach(cipher.subBytes(text), ((el, _0, _1, _2, _3) => (ints.toHexString(el, 2)))));
console.log();
console.log();


/*********************************************************************/

const shiftArr = state.toStateArray4(
	[ '00', '10', '20', '30',
	  '01', '11', '21', '31',
	  '02', '12', '22', '32',
	  '03', '13', '23', '33' ],
	4
)

console.log('Test shiftRows:');
console.log(shiftArr);
console.log();
cipher.shiftRows(4, shiftArr, 4);
console.log(shiftArr);

