#!/usr/bin/env node

/**
 * ./state-test
 * Tests the state array operations
 * for: <https://github.com/lduran2/aes-blocksize512>
 * date: 2018-10-15 T14:21
 * by: Leomar Durán <https://github.com/lduran2>
 */

'use strict';

const state = require('./state.js');

/* the input plaintext */
const text = [ 0, 4,  8, 12,
               1, 5,  9, 13,
               2, 6, 10, 14,
               3, 7, 11, 15];

console.log(state.toStateArray4(text, 4));
console.log(state.toFlatArray(state.toStateArray4(text, 4)));

/* end ./state-test */
